In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from itertools import combinations

In [2]:
db_raw = pd.read_excel('salesCG201718.xls', header=None)

# Shops

In [3]:
shops = db_raw.transpose()[[0,1]].drop([0], axis=0)
shops.rename(columns = {0:'shop', 1:'product'}, inplace=True)
for i in range(1,21,1):
    shops['shop'][2*i] = shops['shop'][2*i-1]

# Months

In [4]:
db_data_month = db_raw.drop([0,1], axis=0)
db_data_month['month'] = db_data_month[0].dt.month
sales_month = db_data_month.groupby('month').sum()
tr_sales_month = sales_month.transpose()

In [5]:
monthly_sales_per_shop = pd.concat([shops, tr_sales_month], axis=1).set_index(['shop', 'product']).transpose()

In [6]:
av_daily_per_month = monthly_sales_per_shop/(6*4)

In [7]:
for i in range(1,13,1):
    monthly_per_month = av_daily_per_month.transpose()[i]
    month_good_order_plot = monthly_per_month.unstack().reindex(monthly_per_month.index.get_level_values(0)).drop_duplicates()

In [8]:
rounded_av_daily_per_month = av_daily_per_month.apply(np.round)

# Volume

In [9]:
for num_s in range(1,21,1):
    rounded_av_daily_per_month[('S'+str(num_s), 'P1')] = rounded_av_daily_per_month[('S'+str(num_s), 'P1')]*0.8
    rounded_av_daily_per_month[('S'+str(num_s), 'P2')] = rounded_av_daily_per_month[('S'+str(num_s), 'P2')]*0.4

In [10]:
vol_av_daily_per_month = rounded_av_daily_per_month.transpose().groupby('shop').sum().reindex(monthly_per_month.index.get_level_values(0)).drop_duplicates().copy()

In [11]:
#renaming
vol_av_daily_per_month.rename(index={'S1': 1, 'S2': 2, 'S3': 3, 'S4': 4, 'S5': 5, 'S6': 6, 'S7': 7, 'S8': 8, 'S9': 9,'S10': 10, 'S11': 11, 'S12': 12, 'S13': 13, 'S14': 14, 'S15': 15, 'S16': 16, 'S17': 17, 'S18': 18, 'S19': 19, 'S20': 20}, inplace=True)
months = ["January","February","March","April","May","June","July","August","September","October","November","December"]
for i in range(1,len(months)+1):
    vol_av_daily_per_month.rename(columns={i: months[i-1]}, inplace=True)

In [12]:
vol_av_daily_per_month

,January,February,March,April,May,June,July,August,September,October,November,December
shop,,,,,,,,,,,,
1,4.4,4.0,4.8,6.8,6.4,6.4,6.4,6.8,5.6,5.6,3.6,2.8
2,4.0,4.0,4.8,6.0,7.2,4.8,6.4,6.8,4.8,5.6,4.0,4.0
3,5.2,6.0,6.8,8.8,8.0,8.0,8.8,8.0,7.6,7.2,5.6,4.8
4,6.0,5.2,7.6,7.2,8.8,8.8,7.2,8.0,6.8,6.4,4.8,4.4
5,4.0,4.8,6.8,5.2,7.2,5.6,6.4,7.6,4.8,5.2,4.0,3.2
6,6.0,6.4,6.0,7.6,7.2,8.8,11.2,9.2,7.6,6.8,5.6,4.8
7,9.2,8.0,11.6,11.2,10.8,10.4,12.4,11.2,11.2,11.2,7.2,6.0
8,7.2,7.6,10.0,12.8,18.8,12.8,13.6,12.4,12.0,10.0,8.0,6.8
9,10.4,9.2,13.6,14.8,16.4,16.0,16.0,11.6,13.2,10.4,8.0,6.4
10,7.6,7.6,7.2,9.6,12.8,9.6,11.2,9.6,10.4,8.8,6.0,6.0
11,8.0,10.0,9.6,12.4,11.6,13.6,14.8,12.8,10.8,8.4,8.0,5.6
12,9.6,7.6,10.4,9.6,14.8,12.0,13.2,14.8,10.4,9.6,8.0,6.0
13,10.0,9.2,10.4,10.4,12.8,14.4,12.8,9.6,11.6,11.6,6.0,6.4
14,9.6,10.0,10.4,14.8,13.2,13.6,17.2,11.6,11.6,12.4,10.4,8.0
15,8.4,8.8,11.2,12.4,13.2,15.2,12.4,12.8,11.6,10.4,8.0,6.8
16,11.2,12.4,15.2,17.2,16.4,15.2,18.0,18.0,14.8,11.6,10.8,9.2
17,8.8,6.8,9.6,10.4,8.0,12.0,11.2,10.4,7.6,8.0,6.4,6.0
18,5.6,5.2,7.6,9.6,7.2,8.0,8.0,7.6,6.8,6.8,5.6,3.6
19,4.4,4.4,5.6,5.2,6.4,6.4,4.8,5.2,5.2,4.8,4.4,3.2
20,5.6,5.2,8.4,9.6,8.8,7.2,8.0,8.4,8.4,6.8,4.4,4.4

In [13]:
vol_av_daily_per_month.to_excel("demand.xlsx")